### inValid Routers - all

GET http://localhost:4000/hello



### New Member Addmission - no no no no no no no no no no no no no no no no no no

POST http://localhost:4000/api/v1/user
Content-Type: application/json

{
    "phone": "01752258545",
    "email": "Shuhagvai@email.com",
    "password": "karnumber"
}



### Update Indivisual Info of a Member - By ID - no no no no no no no no no no no no no no no no no no

PATCH http://localhost:4000/api/v1/user/edit-user/6573e9ebef257a43b9890c59
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzNlZTQ0NjAyMGYyYTEzMWI0YmJlZiIsImlhdCI6MTcwMjcxMTIxNiwiZXhwIjoxNzAyNzk3NjE2fQ.Uh_Lr8Hnuyr5_96qi5b_0D0MNWLyVO8GpEsDiqPjf9g

{
    "roles": ["ADMIN", "AUTHOR"]
}



### Students could see Payment Sheet

GET http://localhost:4000/api/v1/payments/students/sheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzNlZTQ0NjAyMGYyYTEzMWI0YmJlZiIsImlhdCI6MTcwMjcxMTIxNiwiZXhwIjoxNzAyNzk3NjE2fQ.Uh_Lr8Hnuyr5_96qi5b_0D0MNWLyVO8GpEsDiqPjf9g

